# Generated by Django 5.0.7 on 2024-08-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at_label_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
    ]
